"""Generate `dsp_constants.h` for the on-device CMSIS-DSP (arm_math) MFCC.

Single source of truth: the trainer computes MFCCs with `cmsisdsp` using tables
built by `cmsisdsp.mfcc`, and this script emits those SAME tables as C arrays for
the firmware's `arm_mfcc_init_q15` (or `_f32`). Because both sides use identical
tables and identical CMSIS-DSP kernels, the on-device MFCC matches training.

The header contains everything `arm_mfcc_init_q15` needs:
    dctCoefs, filterPos, filterLengths, filterCoefs, windowCoefs
plus geometry #defines (FFT length, mel/DCT counts, sample rate, hop, frames) and,
if `kws_tf.json` is present, the feature-norm mean/std so the device can apply the
exact same standardization before the int8 model.

Usage:
    python src/gen_dsp_constants.py                       # uses config.yaml (+ kws_tf.json)
    python src/gen_dsp_constants.py --precision f32       # float tables instead of Q15
    python src/gen_dsp_constants.py --out ../firmware/dsp_constants.h
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from config import PROJECT_ROOT, load_config
from mfcc_tf import MFCCParams

import cmsisdsp.mfcc as _mfcc
import cmsisdsp.datatype as dt
from cmsisdsp.datatype import F32, Q15
import scipy.signal as sig


def _make_window(fft_length: int, kind: str) -> np.ndarray:
    if kind == "hann":
        return sig.windows.hann(fft_length, sym=False).astype(np.float64)
    if kind == "hamming":
        return sig.windows.hamming(fft_length, sym=False).astype(np.float64)
    raise ValueError(f"unknown window '{kind}' (use 'hann' or 'hamming')")


def _c_array(name: str, ctype: str, values, per_line: int = 12) -> str:
    vals = list(values)

    is_float = ctype in ("float", "float32_t")

    body_lines = []
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i + per_line]

        if is_float:
            body_lines.append(
                "  " + ", ".join(f"{float(v):.8e}f" for v in chunk) + ","
            )
        else:
            body_lines.append(
                "  " + ", ".join(str(int(v)) for v in chunk) + ","
            )

    body = "\n".join(body_lines)
    return f"const {ctype} {name}[{len(vals)}] = {{\n{body}\n}};\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--precision", choices=["q15", "f32"], default="q15")
    ap.add_argument("--window", default=None,
                    help="hann|hamming (default: dsp.window from config, else hann)")
    ap.add_argument("--json", default=str(PROJECT_ROOT / "kws_tf.json"),
                    help="model metadata (for feature_norm mean/std); optional")
    ap.add_argument("--out", default=str(PROJECT_ROOT / "dsp_constants.h"))
    args = ap.parse_args()

    cfg = load_config()
    p = MFCCParams(cfg)
    dsp_cfg = cfg.get("dsp", {}) or {}
    window_kind = (args.window or str(dsp_cfg.get("window", "hann"))).lower()

    fft, nmel, ndct, sr = p.fft_length, p.num_mel_bins, p.num_mfcc, p.sample_rate

    win = _make_window(fft, window_kind)
    ARM_T = Q15 if args.precision == "q15" else F32
    ctype = "q15_t" if args.precision == "q15" else "float32_t"

    filt_len, filt_pos, packed = _mfcc.melFilterMatrix(
        ARM_T, p.lower_hz, p.upper_hz, nmel, sr, fft)
    dct = _mfcc.dctMatrix(ARM_T, ndct, nmel)
    win_c = dt.convert(win, Q15) if args.precision == "q15" else win.astype(np.float32)

    # Optional feature-norm mean/std for on-device standardization.
    norm_lines = ""
    jp = Path(args.json)
    if jp.exists():
        try:
            meta = json.loads(jp.read_text())
            fn = meta.get("feature_norm", {})
            if "mean" in fn and "std" in fn:
                norm_lines = (
                    f"#define MFCC_FEATURE_MEAN ({float(fn['mean']):.8e}f)\n"
                    f"#define MFCC_FEATURE_STD  ({float(fn['std']):.8e}f)\n")
        except Exception:
            pass

    q15_scale = float(dsp_cfg.get("q15_output_scale", 1.0 / 128.0))

    header = f"""/* AUTO-GENERATED by src/gen_dsp_constants.py -- DO NOT EDIT BY HAND.
 *
 * CMSIS-DSP (arm_math) MFCC tables + geometry for the on-device front-end.
 * These are the SAME tables the trainer uses (config.yaml -> dsp), so the device
 * MFCC is mathematically identical to the training features.
 *
 * Backend   : arm_mfcc_{args.precision}
 * Window    : {window_kind} (periodic, length == FFT length)
 * Generated from: config.yaml{' + ' + jp.name if norm_lines else ''}
 *
 * Init on device:
 *   arm_mfcc_init_{args.precision}(&S, MFCC_FFT_LEN, MFCC_NUM_MEL_FILTERS,
 *       MFCC_NUM_DCT_OUTPUTS, mfcc_dct_coefs, mfcc_filter_pos,
 *       mfcc_filter_lengths, mfcc_filter_coefs, mfcc_window_coefs);
 */
#ifndef DSP_CONSTANTS_H
#define DSP_CONSTANTS_H

#include "arm_math.h"

#define MFCC_SAMPLE_RATE        {sr}
#define MFCC_FFT_LEN            {fft}
#define MFCC_FRAME_LEN         {fft}   /* CMSIS windows the full FFT length */
#define MFCC_FRAME_STEP        {p.frame_step}
#define MFCC_NUM_FRAMES        {p.num_frames}
#define MFCC_NUM_MEL_FILTERS   {nmel}
#define MFCC_NUM_DCT_OUTPUTS   {ndct}
#define MFCC_LOWER_HZ          ({float(p.lower_hz):.6f}f)
#define MFCC_UPPER_HZ          ({float(p.upper_hz):.6f}f)
#define MFCC_Q15_OUTPUT_SCALE  ({q15_scale:.8e}f) /* raw q15 MFCC -> float, pre-norm */
{norm_lines}
{_c_array("mfcc_dct_coefs", ctype, dct)}
{_c_array("mfcc_filter_pos", "uint32_t", filt_pos)}
{_c_array("mfcc_filter_lengths", "uint32_t", filt_len)}
{_c_array("mfcc_filter_coefs", ctype, packed)}
{_c_array("mfcc_window_coefs", ctype, win_c)}
#endif /* DSP_CONSTANTS_H */
"""

    out = Path(args.out)
    out.write_text(header)
    print(f"[done] wrote {out}  (arm_mfcc_{args.precision}, {window_kind} window)")
    print(f"       fft={fft} mel={nmel} dct={ndct} frames={p.num_frames} "
          f"sr={sr} hop={p.frame_step}")
    print("       Share this header with the firmware so device MFCC == training MFCC.")


if __name__ == "__main__":
    main()
