"""Fixed-point MFCC front-end built on CMSIS-DSP (arm_math), for on-device parity.

Why this file exists
--------------------
The original front-end (`mfcc_tf.py`) uses `tf.signal`. That is a fine reference,
but it is NOT bit-identical to the MFCC that runs on the nRF5340, which uses ARM's
CMSIS-DSP `arm_mfcc_*` kernels. The teammate handling the firmware/quantization
requires the training features to be "mathematically identical to the one we will
later use on device" — otherwise the model sees one feature distribution in
training and a slightly different one at inference, which quietly wrecks accuracy.

This module computes MFCCs with the OFFICIAL ARM `cmsisdsp` Python wrapper, which
is the very same C source (`arm_math` / CMSIS-DSP) compiled for Python. So the
features produced here match the device to the bit (Q15) or to float rounding
(F32). The Mel/DCT/window tables are generated by `cmsisdsp.mfcc`, and the exact
same tables are exported to `dsp_constants.h` (see `gen_dsp_constants.py`) so the
firmware and the trainer share one source of truth.

Precision
---------
  * arm_q15 (default) : `arm_mfcc_q15` — 16-bit fixed point. Lowest latency and
                        memory on Cortex-M33. This is the "fixed point DSP" the
                        team asked for to reduce preprocessing latency.
  * arm_f32           : `arm_mfcc_f32` — float. Handy parity/debug reference; this
                        is what the firmware used before the fixed-point switch.

Pipeline (per 2 s clip)
-----------------------
  1. FRAME  : slice into windows of `fft_length` samples, hop `frame_step`.
              (CMSIS applies the window over the full FFT length, so the frame
              length IS the FFT length here — differs from the tf.signal path
              which windowed `frame_length` then zero-padded to `fft_length`.)
  2. Q15    : convert each float [-1, 1] window to Q15 int16 (== PCM16 the mic
              gives on device).
  3. MFCC   : `arm_mfcc_q15` -> `num_mfcc` coefficients per frame.

Result: (frames, num_mfcc) — same grid shape the CNN expects.

IMPORTANT: switching the backend changes the feature values, so the model MUST be
retrained and `feature_norm` (mean/std) recomputed. See README.
"""
from __future__ import annotations

import numpy as np

from mfcc_tf import MFCCParams  # reuse the exact same param parsing from config.yaml

# cmsisdsp / scipy are only needed for the arm_* backends. Import lazily with a
# clear error so the tf backend keeps working without them installed.
try:
    import cmsisdsp as dsp
    import cmsisdsp.mfcc as _mfcc
    import cmsisdsp.datatype as dt
    from cmsisdsp.datatype import F32, Q15
    import scipy.signal as sig
    _HAVE_CMSIS = True
except Exception as _e:  # pragma: no cover - only hit when deps are missing
    _HAVE_CMSIS = False
    _IMPORT_ERROR = _e


def _require_cmsis() -> None:
    if not _HAVE_CMSIS:
        raise ImportError(
            "The arm_* DSP backend needs 'cmsisdsp' and 'scipy'. Install with "
            "`pip install cmsisdsp scipy` (cmsisdsp builds a native extension, so "
            f"a C toolchain is required). Original import error: {_IMPORT_ERROR}"
        )


def _make_window(fft_length: int, kind: str) -> np.ndarray:
    """Analysis window of length == FFT length (CMSIS-DSP convention).

    `sym=False` gives the periodic form used for spectral analysis, matching the
    periodic Hann the tf.signal path used and what CMSIS examples use.
    """
    if kind == "hann":
        return sig.windows.hann(fft_length, sym=False).astype(np.float64)
    if kind == "hamming":
        return sig.windows.hamming(fft_length, sym=False).astype(np.float64)
    raise ValueError(f"unknown window '{kind}' (use 'hann' or 'hamming')")


class ArmMFCC:
    """CMSIS-DSP MFCC front-end (Q15 or F32), matching the on-device arm_math.

    Parameters
    ----------
    p        : MFCCParams parsed from config.yaml (sample_rate, fft_length, mel,
               mfcc, fmin/fmax, frame_step ...).
    precision: "q15" (fixed point, default) or "f32".
    window   : "hann" (default) or "hamming". MUST match the window baked into the
               device's dsp_constants.h.
    q15_output_scale: how the raw q15 MFCC output (q8.7-ish int16) is turned into a
               float feature. This is an arbitrary global scale that gets absorbed
               by the mean/std standardization, but it MUST be the same convention
               the firmware uses before normalization. Default 1/128 == q8.7.
    """

    def __init__(self, p: MFCCParams, precision: str = "q15",
                 window: str = "hann", q15_output_scale: float = 1.0 / 128.0):
        _require_cmsis()
        if precision not in ("q15", "f32"):
            raise ValueError(f"precision must be 'q15' or 'f32', got {precision!r}")
        self.p = p
        self.precision = precision
        self.window_kind = window
        self.q15_output_scale = float(q15_output_scale)

        self.fft = int(p.fft_length)
        self.nmel = int(p.num_mel_bins)
        self.ndct = int(p.num_mfcc)
        self.hop = int(p.frame_step)

        win = _make_window(self.fft, window)
        self._neon = bool(dsp.has_neon())

        if precision == "q15":
            self.inst = dsp.arm_mfcc_instance_q15()
            win_q = dt.convert(win, Q15)
            filt_len, filt_pos, packed = _mfcc.melFilterMatrix(
                Q15, p.lower_hz, p.upper_hz, self.nmel, p.sample_rate, self.fft)
            dct = _mfcc.dctMatrix(Q15, self.ndct, self.nmel)
            status = dsp.arm_mfcc_init_q15(
                self.inst, self.fft, self.nmel, self.ndct,
                dct, filt_pos, filt_len, packed, win_q)
            _dtype = dt.Q15
            self._tmp_dtype = np.int16
        else:  # f32
            self.inst = dsp.arm_mfcc_instance_f32()
            win_q = win.astype(np.float32)
            filt_len, filt_pos, packed = _mfcc.melFilterMatrix(
                F32, p.lower_hz, p.upper_hz, self.nmel, p.sample_rate, self.fft)
            dct = _mfcc.dctMatrix(F32, self.ndct, self.nmel)
            status = dsp.arm_mfcc_init_f32(
                self.inst, self.fft, self.nmel, self.ndct,
                dct, filt_pos, filt_len, packed, win_q)
            _dtype = dt.F32
            self._tmp_dtype = np.float32

        if status != 0:
            raise RuntimeError(f"arm_mfcc_init_{precision} failed with status {status}")

        # Scratch buffers, sized exactly like the C code would allocate.
        self._tmp = np.zeros(
            dsp.arm_mfcc_tmp_buffer_size(_dtype, self.fft, 1), dtype=self._tmp_dtype)
        self._tmp2 = None
        if self._neon:
            self._tmp2 = np.zeros(
                dsp.arm_mfcc_tmp_buffer_size(_dtype, self.fft, 2), dtype=self._tmp_dtype)

    # -- framing ------------------------------------------------------------
    def _frames(self, wav: np.ndarray) -> np.ndarray:
        """(n,) float -> (num_frames, fft) with hop == frame_step.

        Truncated/padded to exactly p.num_frames so the feature grid matches the
        model's expected shape regardless of tiny off-by-one clip lengths.
        """
        n = len(wav)
        want = self.p.num_frames
        out = np.zeros((want, self.fft), dtype=np.float64)
        for f in range(want):
            start = f * self.hop
            end = start + self.fft
            if start >= n:
                break
            seg = wav[start:end]
            out[f, : len(seg)] = seg
        return out

    # -- single clip --------------------------------------------------------
    def one(self, wav: np.ndarray) -> np.ndarray:
        """(n,) float32 in [-1, 1] -> (num_frames, num_mfcc) float32."""
        frames = self._frames(np.asarray(wav, dtype=np.float64))
        out = np.empty((frames.shape[0], self.ndct), dtype=np.float32)
        for i, fr in enumerate(frames):
            if self.precision == "q15":
                x = dt.convert(fr, Q15)  # float [-1,1] -> Q15 int16 (== PCM16)
                if self._neon:
                    _err, res = dsp.arm_mfcc_q15(self.inst, x, self._tmp, tmp2=self._tmp2)
                else:
                    _err, res = dsp.arm_mfcc_q15(self.inst, x, self._tmp)
                res = res.astype(np.float32) * self.q15_output_scale
            else:  # f32
                x = fr.astype(np.float32)
                if self._neon:
                    res = dsp.arm_mfcc_f32(self.inst, x, self._tmp, tmp2=self._tmp2)
                else:
                    res = dsp.arm_mfcc_f32(self.inst, x, self._tmp)
                res = np.asarray(res, dtype=np.float32)
            out[i] = res[: self.ndct]
        return out

    # -- batch (drop-in for the tf frontend) --------------------------------
    def batch(self, wavs: np.ndarray) -> np.ndarray:
        """(B, n) float32 -> (B, num_frames, num_mfcc) float32."""
        wavs = np.asarray(wavs)
        if wavs.ndim == 1:
            wavs = wavs[None, :]
        return np.stack([self.one(w) for w in wavs]).astype(np.float32)

    # Callable so it can be used exactly like `frontend(np.stack(batch))`.
    __call__ = batch
